ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ ApplicationKt.main ]
    }
}

database {
    host = "localhost"
    host = ${?POSTGRES_HOST}
    port = 5432
    port = ${?POSTGRES_PORT}
    name = "routedb"
    name = ${?POSTGRES_DB}
    user = "postgres"
    user = ${?POSTGRES_USER}
    password = "postgres"
    password = ${?POSTGRES_PASSWORD}
}

keydb {
    host = "localhost"
    host = ${?KEYDB_HOST}
    port = 6379
    port = ${?KEYDB_PORT}
}
